/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Compressed-Sphere-Bot.glb -o src/components/CompressedSphereBot.jsx 
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/sphere-bot-6c3a32958c2d43cdbf12a7109616bdbe
Title: Sphere Bot
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export const Model = React.forwardRef((props, ref) => {
  const { modelColor, ...restProps } = props
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Compressed-Sphere-Bot.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  // Load metal textures
  const textures = useTexture({
    diffuse: '/textures/metal_plate_02_diff_1k.jpg',
    normal: '/textures/metal_plate_02_nor_gl_1k.jpg',
    roughness: '/textures/metal_plate_02_arm_1k.jpg',
  })

  // Apply textures to all materials in the model and color tint
  React.useEffect(() => {
    if (textures.diffuse && textures.normal && textures.roughness) {
      Object.entries(materials).forEach(([key, material]) => {
        // Skip plane material
        if (key === 'Material_001') {
          material.map = textures.diffuse
          material.normalMap = textures.normal
          material.roughnessMap = textures.roughness
          material.metalness = 0.0
          material.roughness = 0.9
            material.color.setStyle("black")

          return
        }

        if (material.map) {
          material.map = textures.diffuse
          material.normalMap = textures.normal
          material.roughnessMap = textures.roughness
          material.metalness = 0.9
          material.roughness = 0.25

          // Apply color tint if provided
          if (modelColor) {
            material.color.setStyle(modelColor)
          }

          material.needsUpdate = true
        }
      })
    }
  }, [materials, textures, modelColor])

  React.useImperativeHandle(ref, () => ({
    actions
  }), [actions])

  return (
    <group ref={group} {...restProps} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Object_4" scale={0.667}>
          <group name="Hemi" position={[3.195, 7.238, 1.018]} rotation={[0.413, -0.073, -0.79]} />
        </group>
        <primitive object={nodes._rootJoint} />
        <mesh name="Plane_Material_001_0" geometry={nodes.Plane_Material_001_0.geometry} material={materials.Material_001} rotation={[-Math.PI / 2, 0, 0]} scale={0.667} receiveShadow />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Sphere_Bot__Leg_Ao} skeleton={nodes.Object_7.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_9.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_11.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_13.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_15.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_17.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_19.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_21.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_23.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_25.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_27.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_29.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Sphere_Bot__Leg_Nor} skeleton={nodes.Object_31.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Material} skeleton={nodes.Object_33.skeleton} scale={0.667} castShadow receiveShadow />
        <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Material_002} skeleton={nodes.Object_34.skeleton} scale={0.667} castShadow receiveShadow />
      </group>
    </group>
  )
})

Model.displayName = 'CompressedSphereBot'

useGLTF.preload('/models/Compressed-Sphere-Bot.glb')
